server {
    listen 80;

    location /api/ {
        proxy_pass http://backend:8000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        # Authelia v produkci nastaví tyto hlavičky; pro lokální vývoj simulujeme admina
        proxy_set_header Remote-User admin;
        proxy_set_header Remote-Name Admin;
        proxy_set_header Remote-Email admin@local;
    }

    location /media/ {
        alias /media/;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}
